### ISSUE TITLE
metric/utils.py

### ISSUE THREAD

**Issue by ivylinden** [lenscloth/RKD#3]
Hello,Thanks for your work, I run the code, it raise the follwing error:  In metric/utils.py   prod = e @ e.t(): SyntaxError: invalid syntax

**Comment by lenscloth** [comment]
Thank you for showing interest in RKD!

Can you specify your python environment and pytorch version that you are using?

**Comment by ivylinden** [comment]
Hi,I solved the  problem ,It's  because the python version:python 2 not supports the operation  '@'  .Thank you for repling
