### ISSUE TITLE
can't run the "run_distill.py" 

### ISSUE THREAD

**Issue by oxygenman** [lenscloth/RKD#4]
when I run the program follow the Quick Start,it failed with err as blow:
![Screenshot from 2019-07-29 18-15-11](https://user-images.githubusercontent.com/28856502/62040816-e7df7f80-b22c-11e9-8393-c867fc44f2ab.png)

I can't find what's wrong with it, could you help me ?

**Comment by lenscloth** [comment]
Thank you for showing interest in RKD,

For now, the source code does not support KD from GoogleNet => GoogleNet.
You might try ResNet=>ResNet or ResNet => GoogleNet.

**Comment by oxygenman** [comment]
> Thank you for showing interest in RKD,
> 
> For now, the source code does not support KD from GoogleNet => GoogleNet.
> You might try ResNet=>ResNet or ResNet => GoogleNet.

Okay, I have found it, you may better modify the Quick Start instruction, and by the way, thank you very much for your awesome work!

**Comment by lenscloth** [comment]
I changed the README.
Thank you for reporting the issue :)
