### ISSUE TITLE
Hi，could you release the cifar-100 classification experiment?

### ISSUE THREAD

**Issue by oxygenman** [lenscloth/RKD#5]

**Comment by lenscloth** [comment]
I need a time to organize the source code used for CIFAR-100 experiment.
In a mean while you might check this repo: https://github.com/sseung0703/Knowledge_distillation_methods_wtih_Tensorflow 
where RKD is re-implemented and tested in CIFAR-100

**Comment by oxygenman** [comment]
yeah, I know this repo, but I want to work with a pytorch version, hope you will release the original pytorch version earlier, thank you very much for your reply.
