### ISSUE TITLE
Do you have any suggestions  on how to choice the loss ratio of different distill methods?

### ISSUE THREAD

**Issue by oxygenman** [lenscloth/RKD#6]

**Comment by lenscloth** [comment]
You may find the loss ratio at ```examples``` folder, which I used for the experiment on the paper.

Moreover, you can find the details in the paper's experiment section.

**Comment by oxygenman** [comment]
yes,i konw, but i change the code to run classification with other dataset, i would to know some tricks to choose the ratio parameters? or, it is just experiment experience?




| |
yxu_01
邮箱：yxu_01@163.com
|

Signature is customized by Netease Mail Master

On 08/14/2019 20:21, Wonpyo Park wrote:

You may find the loss ratio at example folder, which I used for during the experiment on the paper.

Moreover, you can find the details in the paper's experiment section.

**Comment by lenscloth** [comment]
I choose the ratio by conducting a grid search of the weight.
I would suggest 25 ~ 100, for the weight of RKD losses.

But if you want to do it in a more sophisticated way,
You may calculate the magnitude of gradients of two losses (cross-entropy, RKD).
 and choose the weight.

**Comment by oxygenman** [comment]
okay，thank you!




| |
yxu_01
邮箱：yxu_01@163.com
|

Signature is customized by Netease Mail Master

On 08/14/2019 20:41, Wonpyo Park wrote:

I choose the ratio by conducting a grid search of the weight.
I would suggest 25 ~ 100, for the weight of RKD losses.

But if you want to do it in a more sophisticated way,
You may extract the magnitude of gradients of two losses (cross-entropy, RKD).
and choose the weight.
