### ISSUE TITLE
torch type may not matching in pytorch==1.2

### ISSUE THREAD

**Issue by UnrealPawn** [lenscloth/RKD#7]
Hi~ I think there is a small problem in pairsampler.py. 
In pytorch ==1.0 works fine, but it's not work in pytorch == 1.2.

![1569067728(1)](https://user-images.githubusercontent.com/18569643/65373172-571da100-dcbd-11e9-89ae-5226956e08a5.png)
bool type can not opt with uint8 type 
In  pytorch == 1.2 you can change like this to fix it .
![1569067931(1)](https://user-images.githubusercontent.com/18569643/65373198-9c41d300-dcbd-11e9-9a9c-916b21939c6c.png)
^——^

**Comment by lenscloth** [comment]
@UnrealPawn Thanks for noticing me the updates on pytorch 1.2.0!
I will update if it becomes a fatal issue.
